# Site settings
title: resist lab
email: lab@resist.com
description: > # this means to ignore newlines until "baseurl:"
  resist lab es un espacio de creación y aprendizaje sobre tecnología.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lab.resist.cl" # the base hostname & protocol for your site
twitter_username: resistlab
github_username:  resistlab

# Build settings
markdown: kramdown
